### ISSUE TITLE
please for experiment data

### ISSUE THREAD

**Issue by qxiaofan** [MISTLab/RangeTracker#1]
Thanks for your paper 《Accurate position tracking with a single UWB anchor》,help me a lot.

**Comment by beltrame** [comment]
Unfortunately, I cannot understand what you are saying. Would it be possible to explain in English?

**Comment by qxiaofan** [comment]
> Unfortunately, I cannot understand what you are saying. Would it be possible to explain in English?

I am so sorry, I have reverse my issues. Thanks for your work very much , it is very fantanstic.

**Comment by scorpio-bza** [comment]
@beltrame @yanjundream @ilpincy @ think in the process of studying your thesis, is the derivation of this place wrong in 《Accurate position tracking with a single UWB anchor》?
![image](https://user-images.githubusercontent.com/71498675/121544697-80a3d080-ca3c-11eb-9627-ee886c44ea61.png)

**Comment by scorpio-bza** [comment]
Is it because I calculated the partial derivative wrong? This is my answer. Could you please tell me what is wrong with me?
![38e713d41e7887d8ef5dd78185cf400(1)](https://user-images.githubusercontent.com/71498675/121552082-bfd52000-ca42-11eb-9735-ed690e8344a5.jpg)

**Comment by yanjundream** [comment]
> Is it because I calculated the partial derivative wrong? This is my answer. Could you please tell me what is wrong with me?
> ![38e713d41e7887d8ef5dd78185cf400(1)](https://user-images.githubusercontent.com/71498675/121552082-bfd52000-ca42-11eb-9735-ed690e8344a5.jpg)

@scorpio-bza Thank you for pointing this out. I have checked it and you are right. We probably made the typo or carelessly made the calculation wrong. However,  as we consider the ∆t as a constant variable, the mistake won't affect the following analysis. Anyway, thank you for pointing this. We will correct it and submit a revision in the arxiv.

**Comment by scorpio-bza** [comment]
thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MISTLab/RangeTracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月14日(星期一) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MISTLab/RangeTracker] please for experiment data (#1)





  
Is it because I calculated the partial derivative wrong? This is my answer. Could you please tell me what is wrong with me?
 
 @scorpio-bza Thank you for pointing this out. I have checked it and you are right. We probably made the typo or carelessly made the calculation wrong. However,  as we consider the ∆t as a constant variable, the mistake won't affect the following analysis. Anyway, thank you for pointing this. We will correct it and submit a revision in the arxiv.
